[workspace]
members = [
    "rust/bench-core",
    "rust/adapters/umadb",
    "rust/adapters/dummy",
    "rust/adapters/kurrentdb",
    "rust/testcontainers",
    "rust/adapters/eventsourcingdb",
    "rust/cli",
]
resolver = "2"
