[package]
name = "axonserver-client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
tonic = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1"
anyhow = "1"

[build-dependencies]
tonic-build = "0.12"
